config/routes.rb
Rails.application.routes.draw do
  root to: 'public#home'

  resources :public
    resources :wallets do
      member do
        patch 'confirm'
        get :generate_pdf
      end
    resources :incomes
    resources :spendings
    end

  devise_for :users, controllers:
    {
      sessions: 'user/sessions',
      registrations: 'user/registrations'
    }
  devise_scope :user do
    put "/user/invitation", :to => "devise/invitations#update"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :incomes, dependent: :destroy
  has_many :spendings, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30}
  validate :name_presence

  private
  def name_presence
    errors.add(:name, "must be present") if name.blank?
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(current_user.id)
    @wallets = @user.wallets.all
  end
  def show
    @user = User.find(current_user.id)
    @wallet = @user.wallets.find(params[:id])
    @incomes = @wallet.incomes.all
    @spendings = @wallet.spendings.all
    @transactions = (@incomes + @spendings).sort_by(&:created_at).reverse

    @dostepnesrodki = 0
    @dostepnesrodki = @incomes.sum(:amount)
    @dostepnesrodki -=@spendings.sum(:amount)
    @spending_data = @spendings.group(:category_id).sum(:amount)

    # Pobierz wszystkie kategorie z modelu Category
    @categories = Category.all

    # Utwórz pusty hash, który będzie przechowywał dane do wykresu kołowego
    @chart_data = {}

    # Przeiteruj przez dane o wydatkach
    @spending_data.each do |category_id, amount|
      # Znajdź nazwę kategorii na podstawie jej ID
      category_name = @categories.find_by(id: category_id)&.name

      # Dodaj dane do wykresu kołowego tylko, jeśli znaleziono nazwę kategorii
      if category_name
        @chart_data[category_name] = amount
      end
    end
  end

  def new
    @user=User.find(params[:user_id])
    @wallet=@user.wallets.new
  end
  def create
    @user = User.find(current_user.id)
    @wallet = @user.wallets.create(wallet_params)
    redirect_to wallet_path(@wallet)

    end
  def confirm
    @wallet = Wallet.find(params[:id])
    user_id = params[:wallet][:user_id]
    @user = User.find(user_id)
    if @user.wallets.where(name: @wallet.name) == []
      @user.wallets << @wallet
      flash.alert = "Pomyślnie dodano użytkownika #{@user.nick} do portfela #{@wallet.name}"
    else

      flash.alert = "Użytkownik #{@user.nick} jest już przypisany do tego portfela"
      end
    redirect_to @wallet
  end

  def destroy
    @user = User.find(current_user.id)
    @wallet = Wallet.find(params[:id])
    @wallet.destroy
    redirect_to wallets_path
  end

  def generate_pdf
    @user = User.find(current_user.id)
    @wallet = @user.wallets.find(params[:id])
    @incomes = @wallet.incomes.all
    @spendings = @wallet.spendings.all
    @transactions = (@incomes + @spendings).sort_by(&:created_at).reverse

    @dostepnesrodki = 0
    @dostepnesrodki = @incomes.sum(:amount)
    @dostepnesrodki -=@spendings.sum(:amount)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new

        pdf.font_families["pdfFont"] = {
          normal: "#{Rails.root}/app/assets/fonts/Roboto-Bold.ttf"
        }

        pdf.font "pdfFont"


        pdf.text "Budzet domowy - #{@wallet.name}"

        pdf.move_down 30
        pdf.text "Historia Transakcji:"
        pdf.move_down 10

        @transactions.each do |transaction|
          pdf.text "#{transaction.created_at.strftime('%Y-%m-%d %H:%M:%S')}"
          if transaction.is_a? Income
            pdf.text "Przychód:"
          else
            pdf.text "Wydatek:"
          end
          pdf.text "#{transaction.title} #{transaction.amount}zł"
          pdf.move_down 30
        end
        pdf.text "#{@wallet.name} - dostępne środki: #{@dostepnesrodki}zł"

        send_data pdf.render, filename: 'wallet.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end
  private

  def wallet_params
    params.require(:wallet).permit(:name)
  end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/index.html.erb
<!DOCTYPE html>
<html>
    <%= stylesheet_link_tag "main_wallet.css" %>
    <head>
      <title>Witaj!</title>
      <link href='http://fonts.googleapis.com/css?family=Poppins&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
      <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    </head>
    <body>
        <div>
          <%= image_tag "Wersja5.png", class: "logo" %>
        </div>
        <div class="box">
          <div class="gora">
                <h2>Budżet domowy</h2>
                <h2>Witaj <%= @user.nick %>!</h2>
          </div>
          <div class="dol">
            <div class="lewa">
                  <h3>Dostępne portfele</h3>
                  <div class="lista"><ul>
                    <% @wallets.each do |wallet| %>
                      <li>
                        <%= link_to wallet.name, wallet, class: "linczek" %>
                      </li>
                    <%end%>
                  </ul></div>
                <label><button type="button" class="guziki"><%= link_to "Dodaj nowy portfel", new_wallet_path(user_id: @user.id), class: "guziki" %></button></label>
              </div>
              <div class="prawa">
                  <h3>Zarządzanie kontem</h3>
                  <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: "buttonNavVer" %>
                <label><button type="button" class="usuwanie"><%= link_to "USUŃ KONTO", public_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Napewno chcesz usunąć użytkownika?\n(Czynność ta nie usunie porfeli)"
                }, class: "usuwanie" %></button></label>
              </div>
          </div>
        </div>
    </body>
</html>

app/views/wallets/new.html.erb
<!DOCTYPE html>
<html>
  <%= stylesheet_link_tag "new_wallet.css" %>
  <head>
    <title>Nowy portfel</title>
    <link href='http://fonts.googleapis.com/css?family=Poppins&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
  </head>
  <body>
    <div>
      <%= image_tag "Wersja5.png", class: "logo" %>
    </div>
    <div class="box">
      <h2>Dodaj Portfel dla: "<%= @user.nick %>"</h2>
      <div>
        <%=form_with model: [@wallet] do |form| %>
          <div class="field">
            <ion-icon name="pricetag-outline"></ion-icon>
            <%= form.label :name, class: "etykieta" %>
            <%= form.text_field :name, class: "okno" %>
          </div>
        <% @wallet.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.submit 'Stwórz', class: "guzik" %>
        <% end %>
      </div>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/wallets/show.html.erb
<!DOCTYPE html>
<html>
  <%= stylesheet_link_tag "show_wallet.css" %>
  <head>
    <title>Portfel</title>
    <link href='http://fonts.googleapis.com/css?family=Poppins&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
  </head>
  <body>
    <div>
      <%= image_tag "Wersja5.png", class: "logo" %>
    </div>
    <div class="rama">
      <div class="gornagora">
        <h2><%= @wallet.name%></h2>
      </div>
      <div class="gorna">
        <div class="lewe">
          <h3>Dostępne portfele</h3>
          <div class="lista">
            <ul>
              <% @user.wallets.each do |wallet| %>
              <li>
                <%= link_to wallet.name, wallet, class: "linczek" %> <label><button type="button" class="usun"><%= link_to "Usuń", wallet_path(wallet), data: {
                turbo_method: :delete,
                turbo_confirm: "Napewno chcesz usunąć porfel i całą jego historię?"
              }, class: "usun" %></button></label>
              </li>
              <%end%>
              <button type="button" class="guziki"><%= link_to "Dodaj nowy portfel", new_wallet_path(user_id: @user.id), class: "guziki" %></button>
            </ul>
          </div>
        </div>
        <div class="srodek">
          <h3>Historia Transakcji</h3>
          <div class="lista">
            <ul>
              <% @transactions.each do |transaction| %>
                <li>
                  <%= transaction.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
                  <%if transaction.is_a? Income  %>
                    <d style="color:#2cb62c">Przychód:</d>
                  <% else %>
                    <d style="color:#ee2020">Wydatek:</d>
                  <% end %>
                  <b><%= transaction.title %></b> <%= transaction.amount %>zł
                </li>
              <%end%>
            </ul>
          </div>
          <button type="button" class="guziki"><%= link_to "Dodaj Wydatek", new_wallet_spending_path(wallet_id: @wallet.id), class: "guziki" %></button>
          <button type="button" class="guziki"><%= link_to "Dodaj Przychód", new_wallet_income_path(wallet_id: @wallet.id), class: "guziki" %></button>
        </div>
        <div class="prawe">
          <h3>Zarządzanie kontem</h3>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: "buttonNavVer" %>
          <h3>Zarządzanie portfelem</h3>
          <a class="etykiet">Dodaj użytkownika do tego portfela:</a>
            <%= form_with(model: @wallet, url: confirm_wallet_path(@wallet)) do |form| %>
            <div class="rozwijana"><%= form.collection_select :user_id, User.all, :id, :nick, class: "rozwijana" %></div>
              <%= form.submit 'Potwierdź', class: "guziki"%>
            <% end %>
        </div>
      </div>
      <div class="dolna">
        <%= pie_chart @chart_data, library: { title: { text: 'Sum of Spending Amounts by Category' } } %>
        <div><h3><%= @wallet.name %> - dostępne środki: <%= @dostepnesrodki.round(2) %>zł</h3>
          <button type="button" class="guziki"><%= link_to 'Wygeneruj PDF', generate_pdf_wallet_path(@wallet, format: :pdf), class: "pdf" %></button></div>
      </div>
    </div>
  </body>
</html>